// === MINA Block Puzzle - Visual Themes ===

import { ThemeColors, ThemeName } from '../types/game';

export const THEMES: Record<ThemeName, ThemeColors> = {
  classic: {
    name: 'classic',
    label: '✨ Classique',
    bg: '#0f0e1a',
    surface: '#1a1930',
    card: '#232145',
    gridBg: '#1e1c3a',
    gridLine: '#2d2a55',
    text: '#e2e0ff',
    muted: '#8b88b0',
  },
  night: {
    name: 'night',
    label: '🌙 Nuit',
    bg: '#0a0a0f',
    surface: '#111118',
    card: '#1a1a24',
    gridBg: '#141420',
    gridLine: '#222235',
    text: '#d4d4e8',
    muted: '#6b6b8a',
  },
  sunset: {
    name: 'sunset',
    label: '🌅 Coucher de soleil',
    bg: '#1a0f1e',
    surface: '#261830',
    card: '#352040',
    gridBg: '#2a1535',
    gridLine: '#3d2550',
    text: '#f0ddf5',
    muted: '#a078b0',
  },
};

export const ACHIEVEMENTS = [
  {
    id: 'first_clear',
    name: 'Première ligne !',
    description: 'Compléter ta première ligne',
    icon: '⭐',
    target: 1,
    type: 'lines',
  },
  {
    id: 'ten_lines',
    name: 'En route !',
    description: 'Compléter 10 lignes',
    icon: '🔥',
    target: 10,
    type: 'lines',
  },
  {
    id: 'fifty_lines',
    name: 'Expert',
    description: 'Compléter 50 lignes',
    icon: '💎',
    target: 50,
    type: 'lines',
  },
  {
    id: 'hundred_lines',
    name: 'Maître',
    description: 'Compléter 100 lignes',
    icon: '👑',
    target: 100,
    type: 'lines',
  },
  {
    id: 'score_500',
    name: 'Bon score',
    description: 'Atteindre 500 points',
    icon: '🎯',
    target: 500,
    type: 'score',
  },
  {
    id: 'score_1000',
    name: 'Score épique',
    description: 'Atteindre 1000 points',
    icon: '🏆',
    target: 1000,
    type: 'score',
  },
  {
    id: 'score_5000',
    name: 'Légendaire',
    description: 'Atteindre 5000 points',
    icon: '🌟',
    target: 5000,
    type: 'score',
  },
  {
    id: 'combo_2',
    name: 'Combo !',
    description: 'Faire un combo x2',
    icon: '⚡',
    target: 2,
    type: 'combo',
  },
  {
    id: 'combo_3',
    name: 'Triple combo !',
    description: 'Faire un combo x3',
    icon: '💥',
    target: 3,
    type: 'combo',
  },
  {
    id: 'multi_clear',
    name: 'Multi-clear',
    description: 'Supprimer 2+ lignes en un coup',
    icon: '🎆',
    target: 2,
    type: 'multiClear',
  },
];
